### PR TITLE
#6 remove inappropriate for loops

### PR DESCRIPTION
**Pull request by y-aok**
alter list comprehension when making "assignees" update request.

### CODE REVIEW

**Comment by y-aok** [comment]
oops. sorry will re-test this one.

**Comment by y-aok** [comment]
excuse me, but could you check if this build failure is related to this PR?
I suspect not, since I get same failure when running travis build on my master branch...

**Comment by jpetrucciani** [comment]
Looks like the apiary I was using for the tests had been changed on the ClickUp API page - I've updated that string on master and the tests are all passing again for master.

**Comment by y-aok** [comment]
thank you for update! glad i had not broke your tests...

**Comment by y-aok** [comment]
This PR is replaced within #8

**Pull request closed without merging**
